
spring:
  r2dbc:
    url: r2dbc:h2:mem:///contact_db?options=MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    name: sa
    password:
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG