spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:agenda_db
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create