spring:
  data:
    mongodb:
      host: "localhost:27017"
      database: "mongodb-demo"
      username: "mongoUser"
      password: "mongoUser@"

  kafka:
    bootstrap-servers: "localhost:29092"
    consumer:
      group-id: "myGroup"


