spring:
  data:
    mongodb.uri: mongodb://mongoUser:mongoUser@localhost:27017/job-batch
  datasource:
      url: jdbc:postgresql://localhost:5432/job-batch
      username: postgresUser
      password: postgresUser
  batch:
    jdbc.initialize-schema: always