spring:
  kafka:
    bootstrap-servers: localhost:29092"
    template.default-topic: person-topic
    consumer:
      group-id: person-group
  data:
    mongodb.uri: mongodb://mongoUser:mongoUser@localhost:27017/job-batch
  datasource:
      url: jdbc:postgresql://localhost:5432/job-batch
      username: postgresUser
      password: postgresUser
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always